export type Experience = {
  id: string;
  title: string;
  company: string;
  location: string;
  start: string;
  end: string;
  description: string;
};
export type Education = {
  id: string;
  degree: string;
  description?: string;
  school: string;
  location: string;
  start: string;
  end: string;
};
export type Project = { id: string; name: string; description: string; tech: string; url?: string; github?: string };
export type Certification = { id: string; name: string; organization: string; date: string; url: string };
export type Language = { id: string; language: string; proficiency: string };
export type Achievement = { id: string; text: string };
export type Volunteer = { id: string; role: string; organization: string; location: string; start: string; end: string; description: string };
export type Reference = { id: string; name: string; relationship: string; email: string; phone: string };
export type DesignSettings = { accent: string; font: string; spacing: number; bodyFontSize: number; nameFontSize: number; headingFont?: string; secondaryAccent?: string; background?: string };
export type AuthUser = { id: string; email: string; role: "admin" | "user" };
export type CVData = {
  importedSource?: string;
  importedFilename?: string;
  id: string;
  name: string;
  template: string;
  fullName: string;
  title: string;
  email: string;
  phone: string;
  location: string;
  website: string;
  linkedin: string;
  photo: string;
  originalPhoto?: string;
  summary: string;
  experience: Experience[];
  education: Education[];
  skills: string[];
  expertise: string[];
  projects: Project[];
  certifications: Certification[];
  languages: Language[];
  achievements: Achievement[];
  volunteer: Volunteer[];
  references: Reference[];
  design: DesignSettings;
  sections: string[];
  templateConfig?: Template;
};
export type Template = {
  id: string;
  name: string;
  category: string;
  description: string;
  ats?: boolean;
  style: string;
  design?: DesignSettings;
  status?: "draft" | "published";
  version?: number;
  layout?: "single" | "two-column";
  sidebarPosition?: "left" | "right";
  sidebarWidth?: number;
  headerAlign?: "left" | "center";
  showPhoto?: boolean;
  photoShape?: "circle" | "rounded" | "square";
  pageSize?: "a4" | "letter";
  pageMargin?: number;
  density?: "compact" | "standard" | "relaxed";
  divider?: "line" | "accent" | "none";
  skillStyle?: "chips" | "plain" | "bars";
  contactStyle?: "inline" | "stacked";
  sections?: string[];
  sidebarSections?: string[];
  sectionLabels?: Record<string, string>;
};
